#+TITLE: Lesson6 - Programming language

* DDOS
Using three machines:
- Attacker - The attacker will send 10K tcp syn packets to the target machine,
in a 100 iterations loop. Total of 1M packets.
- Target - running an /apache/ server.
- Monitor - will send pings to the server during the attack.

** Attacker
The attacker will run two types of programs, one in C and one in Python.
For each program we will measure:
- The time the attacker needs to send a packet (avg).
- The ping’s RTT from the monitor. You will have to send one ping every 5 seconds.
** Measuerments
*** Syn packets
The above measurements would appear in measurement files, in the following scheme:
**** /syns_results_c.txt/ - containing each syn request (as well as index of the request) sent from the C program and the time it took to send it
seperated by a new line. At the end of the file a measurement of how long it took for the program to send all the packets, and the average time to send a packet.
**** /syns_results_p.txt/ ,  same as above, but for the Python program. 
*** Ping
**** /ping_results_c.txt/
containing all the ping requests generated by the Monitor machine, while the Attacker attacked using the C program. Each ping request should be separated with newline. At the end of the file, you should add the average ping’s RTT.
**** /pings_results_p.txt/
same as above, but while the Attacker used the Python program.
** Graphs
Using the /matlplotlib/ graph we will describe the 2 measuerments, for C and for Python.
*** Syn Packets
 * Syn_pkts_c.png & Syn_pkts_p.png : The graph should describe the time needed for the attacker to send a packet. The x axis should be the time needed to send a packet. The y axis will represent the number of packets sent. One graph for the Python attack and another for the C attack.

 * The y axis should be logarithmic, and the x axis should be distinguishable.

 * Report - short report describing the results, with STD (standard deviation) and average.

 * Exaplain the differences.
*** Ping
Create matplotlib graphs describing the 2 measuerments for C and for Python.
- Pings_c.png & Pings_p.png : The graph should describe the RTT for the ping requests. The x axis should be the RTT in milliseconds. The y axis will represent the number of pings. One graph for the Python attack and another for the C attack.
- The y axis should be logarithmic, and the x axis should be distinguishable.
- You’ll also need to create a short report describing the results, with STD and average.
- Explain the differences.
**   Submission
All files will be uploaded to ~204652_measuere.zip~ which will include:
 - Attach files:
   + ~Attack.py~
   + ~attack.c~
   + DDOS.pdf - report of the lab.
   + Graphs for C:
     - ~Syn_pkts_c.png~. 
     - ~Pings_c.png~.
   + Graphs for Python:
     - ~Syn_pkts_p.png~
     - ~Pings_p.png~
   + Results for Python:
     - ~syns_results_p.txt~
     - ~pings_results_p.txt~
   + Results for C:
     - ~syns_results_c.txt~
     - ~pings_results_c.txt~

* TODO My progression
- [ ] Task three - Victim :: install apache server (No protections). 
- [ ] Task  :: 
  
* Before submitting
